name: swiftroutes_ai_transport
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0  
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  confetti: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/screenshot.png
    - lib/assets/images/logo.png
    - lib/assets/images/background.png
    - lib/assets/images/download.png